apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: argocd-pipeline
  title: ArgoCD Pipeline
  description:
    Build And Deliver Software on Kubernetes Using Gitops
  tags:
    - Recommended
    - React
spec:
  owner: perry.manuk@trivago.com
  templater: cookiecutter
  type: kubernetes deployment
  path: './example'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Description of the component
